- name: Issue show commands
  hosts: switches
  connection: network_cli
  tasks:
    - name: Show ip int brief
      ios_command:
        commands:
          - show ip int brief
       # provider:
       #   host: switches
       #   port: 22
       #   authorize: yes
       #   auth_pass: Cenare2203$
       #   username: cenare
       #   password: Cenare2203$
      register: if_data

    - name: Interfaces output
      debug:
        var: if_data['stdout_lines'][0]
